### ISSUE TITLE
missing  Siticone.UI

### ISSUE THREAD

**Issue by darklunny** [Zenixas/CsharpCheatLoader#1]
where do i find Siticone.UI

**Comment by Zenixas** [comment]
> where do i find Siticone.UI

You could have found it just by googling it, here's the dll I used:
https://cdn.discordapp.com/attachments/851909533306454017/871035538327613500/Siticone.UI.dll

**Comment by darklunny** [comment]
ok thanks

**Comment by darklunny** [comment]
where do i put it
?

**Comment by darklunny** [comment]
![image](https://user-images.githubusercontent.com/84659156/127744591-0a82494b-1a85-45d8-945a-ebbfe020ebb7.png)
wot do i put here

**Comment by Zenixas** [comment]
> ![image](https://user-images.githubusercontent.com/84659156/127744591-0a82494b-1a85-45d8-945a-ebbfe020ebb7.png)
> wot do i put here

you don't need to edit the auth.cs file, to link it to your auth panel you need to looks in login.cs

**Comment by darklunny** [comment]
ok

**Comment by darklunny** [comment]
![image](https://user-images.githubusercontent.com/84659156/127744791-80072897-43f2-455e-9908-40ce659f8d5c.png)
i get this

**Comment by darklunny** [comment]
??

**Comment by Zenixas** [comment]
you need connect it to your web app on:
https://biitez.dev/services/authenty/

Right now it is not able to connect to the authentication server
